name: 'Linux AArch64'
on: push

jobs:
  linux-sdk:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Prepare ccache timestamp
        id: ccache_cache_timestamp
        shell: cmake -P {0}
        run: |
          string(TIMESTAMP current_date "%Y-%m-%d-%H;%M;%S" UTC)
            message("::set-output name=timestamp::${current_date}")
      - name: ccache cache files
        uses: actions/cache@v1.1.0
        with:
          path: .ccache
        key: linux-aarch64-ccache-${ { steps.ccache_cache_timestamp.outputs.timestamp } }
        restore-keys: |
            linux-aarch64-ccache-
      - name: Build
        shell: bash
        run: |
          docker run \
           -e CCACHE_COMPRESS=1 \
           -e CCACHE_MAXSIZE=10.0G \
           -e CCACHE_CPP2=1 \
           -e CCACHE_DIR=/ccache \
           -v $GITHUB_WORKSPACE:/work \
           -v $HOME/.ccache:/ccache \
          --rm liefproject/manylinux2014-aarch64:base bash /work/scripts/docker/linux-aarch64.sh



