name: 'Linux AArch64'
on: push

jobs:
  linux-sdk:
    runs-on: ubuntu-latest
    container:
      image: liefproject/manylinux2014-aarch64
      env:
        CCACHE_DIR: /ccache
      volumes:
        - $GITHUB_WORKSPACE:/src
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: /src/scripts/docker/linux-x86-64.sh


