name: 'Linux AArch64'
on: push

jobs:
  linux-sdk:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        shell: bash
        run: |
          docker run \
           -e CCACHE_DIR=/ccache \
           -v $GITHUB_WORKSPACE:/work \
          --rm liefproject/android-arm64:base bash /work/scripts/docker/android-aarch64.sh



